- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Install Certbot via Snap
  snap:
    name: certbot
    classic: yes

- name: Generate HTTPS certificate
  command: certbot certonly --nginx --non-interactive --agree-tos --email suporteinaclick@gmail.com -d inaclick.com.br -d api.inaclick.com.br -d dashboard.inaclick.com.br

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
