- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present

- name: Copy Fail2Ban configuration file
  template:
    src: ~/secrets/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted