- name: Ensure .ssh directory exists
  file:
    path: "~/.ssh"
    state: directory

- name: Move id_ed25519 to .ssh directory
  become: yes
  shell: cp ~/secrets/github/id_ed25519 ~/.ssh/

- name: Move id_ed25519.pub to .ssh directory
  become: yes
  shell: cp ~/secrets/github/id_ed25519.pub ~/.ssh/

- name: Add id_ed25519 to SSH agent
  become: yes
  shell: |
    eval "$(ssh-agent)"
    ssh-add ~/.ssh/id_ed25519
