- name: Clone inaclick backend service
  git:
    repo: git@github.com:zadhart/inaclickPythonApi.git
    dest: ~/inaclickPythonApi

- name: Clone inaclick web
  git:
    repo: git@github.com:Lauzzener/inaclickWeb.git
    dest: ~/inaclickWeb
